export const cy = {
  bulkUnsubscribeTitle: "Datdanysgrifio Swmp",
  bulkUnsubscribeHeading: "Datdanysgrifio Swmp",
  tabAllSubscriptions: "Pob tanysgrifiad",
  tabSubscriptionsByCase: "Tanysgrifiadau yn ôl achos",
  tabSubscriptionsByCourt: "Tanysgrifiadau yn ôl llys neu dribiwnlys",
  tableHeaderCaseName: "Enw'r achos",
  tableHeaderPartyName: "Enw'r parti (partïon)",
  tableHeaderReferenceNumber: "Cyfeirnod",
  tableHeaderDateAdded: "Dyddiad wedi'i ychwanegu",
  tableHeaderCourtName: "Enw'r llys neu'r tribiwnlys",
  bulkUnsubscribeButton: "Dileu swmp o danysgrifiadau",
  emptyStateMessage: "Nid oes gennych unrhyw danysgrifiadau yn y categori hwn.",
  noCaseSubscriptions: "Nid oes gennych unrhyw danysgrifiadau achos.",
  noCourtSubscriptions: "Nid oes gennych unrhyw danysgrifiadau llys neu dribiwnlys.",
  notAvailable: "Ddim ar gael",
  errorSummaryTitle: "Mae yna broblem",
  errorNoSelectionMessage: "Mae angen o leiaf un tanysgrifiad",
  errorNoSelectionHref: "#subscriptions"
};
