export const en = {
  bulkUnsubscribeTitle: "Bulk unsubscribe",
  bulkUnsubscribeHeading: "Bulk unsubscribe",
  tabAllSubscriptions: "All subscriptions",
  tabSubscriptionsByCase: "Subscriptions by case",
  tabSubscriptionsByCourt: "Subscriptions by court or tribunal",
  tableHeaderCaseName: "Case name",
  tableHeaderPartyName: "Party name(s)",
  tableHeaderReferenceNumber: "Reference number",
  tableHeaderDateAdded: "Date added",
  tableHeaderCourtName: "Court or tribunal name",
  bulkUnsubscribeButton: "Bulk unsubscribe",
  emptyStateMessage: "You do not have any subscriptions in this category.",
  noCaseSubscriptions: "You do not have any case subscriptions.",
  noCourtSubscriptions: "You do not have any court or tribunal subscriptions.",
  notAvailable: "Not available",
  errorSummaryTitle: "There is a problem",
  errorNoSelectionMessage: "At least one subscription must be selected",
  errorNoSelectionHref: "#subscriptions"
};
