export const en = {
  backLink: "Back",
  pageTitle: "Find, update and delete a user",
  filterHeading: "Filter",
  selectedFiltersHeading: "Selected filters",
  emailLabel: "Email",
  userIdLabel: "User ID",
  userIdHint: "Must be an exact match",
  userProvenanceIdLabel: "User Provenance ID",
  userProvenanceIdHint: "Must be an exact match",
  roleLabel: "Role",
  rolesLabel: "Roles",
  provenanceLabel: "Provenance",
  provenancesLabel: "Provenances",
  applyFiltersButton: "Apply filters",
  clearFiltersButton: "Clear filters",
  tableHeadEmail: "Email",
  tableHeadRole: "Role",
  tableHeadProvenance: "Provenance",
  tableHeadManage: "",
  manageLink: "Manage",
  paginationPrevious: "Previous",
  paginationNext: "Next",
  paginationLabel: (current: number, total: number) => `Page ${current} of ${total}`,
  resultsCount: (count: number) => `${count} user${count === 1 ? "" : "s"} found`,
  noResultsError: "No users could be found matching your search criteria. Try adjusting or clearing the filters.",
  errorSummaryTitle: "There is a problem",
  roleVerified: "Verified",
  roleCtscAdmin: "CTSC Admin",
  roleLocalAdmin: "Local Admin",
  roleSystemAdmin: "System Admin",
  provenanceCftIdam: "CFT IdAM",
  provenanceSso: "SSO",
  provenanceB2c: "B2C",
  provenanceCrimeIdam: "Crime IdAM"
};
