-- Note: Artefacts reference list_types via FK constraint
-- List types are created by test-support routes during E2E tests
-- Artefacts are created by individual tests as needed
-- This seed file intentionally left minimal to avoid conflicts
