nodeLinker: node-modules

npmScopes:
  hmcts-cft:
    npmRegistryServer: "https://pkgs.dev.azure.com/hmcts/Artifacts/_packaging/hmcts-lib/npm/registry/"
    npmAlwaysAuth: true

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - arm64
    - x64
