export const cy = {
  title: "Crynodeb llwytho data cyfeirio i fyny",
  pageTitle: "Crynodeb llwytho data cyfeirio i fyny",
  fileLabel: "Welsh placeholder",
  changeLink: "Welsh placeholder",
  confirmButtonText: "Welsh placeholder",
  previewTitle: "Welsh placeholder",
  locationIdHeader: "Welsh placeholder",
  locationNameHeader: "Welsh placeholder",
  welshLocationNameHeader: "Welsh placeholder",
  emailHeader: "Welsh placeholder",
  contactNoHeader: "Welsh placeholder",
  jurisdictionHeader: "Welsh placeholder",
  subJurisdictionHeader: "Welsh placeholder",
  regionHeader: "Welsh placeholder",
  provenanceHeader: "Welsh placeholder",
  provenanceLocationIdHeader: "Welsh placeholder",
  provenanceLocationTypeHeader: "Welsh placeholder",
  errorSummaryTitle: "Welsh placeholder",
  errorTitle: "Welsh placeholder"
};
