apiVersion: v2
appVersion: '1.0'
description: A Helm chart for future-hearings-cath crons
name: future-hearings-cath-crons
home: https://github.com/hmcts/future-hearings-cath
version: 0.0.1
dependencies:
  - name: job
    version: 2.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
