apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Court and Tribunal Hearings Service crons
name: cath-crons
home: https://github.com/hmcts/cath-service
version: 0.0.1
dependencies:
  - name: job
    version: 2.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
