export const cy = {
  title: "Llwytho â llaw",
  fileUploadLabel: "Llwytho ffeil csv, doc, docx, htm, html, json, neu pdf â llaw, uchafswm maint 2MB",
  courtLabel: "Enw'r llys neu'r tribiwnlys",
  listTypeLabel: "Math o restr",
  listTypePlaceholder: "Dewiswch fath o restr",
  hearingStartDateLabel: "Dyddiad dechrau'r gwrandawiad",
  hearingStartDateHint: "Er enghraifft, 16 01 2022",
  sensitivityLabel: "Sensitifrwydd",
  languageLabel: "Iaith",
  displayFromLabel: "Dangos y ffeil o",
  displayFromHint: "Er enghraifft, 27 01 2022",
  displayToLabel: "Dangos y ffeil tan",
  displayToHint: "Er enghraifft, 18 02 2022",
  continueButton: "Parhau",
  errorSummaryTitle: "Mae yna broblem",
  pageHelpTitle: "Cymorth tudalen",
  pageHelpLists: "Rhestrau",
  pageHelpListsText:
    "Rhaid i chi sicrhau eich bod chi ond yn llwytho un ffeil sy'n cynnwys yr holl wrandawiadau ar gyfer enw'r Llys neu'r Tribiwnlys a'r math o restr. Dylai hyn gynnwys pob barnwr ac ystafell lys mewn un ddogfen.",
  pageHelpSensitivity: "Sensitifrwydd",
  pageHelpSensitivityText: "Mae angen i chi nodi pa grŵp defnyddwyr y dylai eich dogfen fod ar gael iddynt:",
  pageHelpSensitivityPublic: "Cyhoeddus",
  pageHelpSensitivityPublicText: "Cyhoeddiad ar gael i bob defnyddiwr.",
  pageHelpSensitivityPrivate: "Preifat",
  pageHelpSensitivityPrivateText: "Cyhoeddiad ar gael i bob defnyddiwr wedi'u dilysu e.e. Gweithwyr proffesiynol cyfreithiol a'r cyfryngau.",
  pageHelpSensitivityClassified: "Dosbarthedig",
  pageHelpSensitivityClassifiedText:
    "Cyhoeddiad ar gael i ddefnyddwyr wedi'u dilysu sydd mewn grŵp sy'n gymwys i weld y rhestr honno e.e. Rhestr y wasg SJP ar gael i'r Cyfryngau",
  pageHelpDisplayFrom: "Dangos o",
  pageHelpDisplayFromText:
    "Hwn fydd y dyddiad y bydd y cyhoeddiad ar gael ohono, os defnyddir dyddiad heddiw bydd yn cael ei ddangos ar unwaith. Os defnyddir dyddiad yn y dyfodol, bydd yn cael ei ddangos o 00:01 ar y dyddiad hwnnw.",
  pageHelpDisplayTo: "Dangos tan",
  pageHelpDisplayToText: "Hwn fydd y dyddiad olaf y bydd y cyhoeddiad ar gael. Bydd yn cael ei ddangos tan 23:59 ar y dyddiad hwnnw.",
  dayLabel: "Diwrnod",
  monthLabel: "Mis",
  yearLabel: "Blwyddyn",

  errors: {
    fileRequired: "Darparwch ffeil",
    fileType: "Rhaid i'r ffeil a ddewiswyd fod yn csv, doc, docx, htm, html, json, neu pdf",
    fileSize: "Rhaid i'r ffeil a ddewiswyd fod yn llai na 2MB",
    courtRequired: "Rhaid i enw'r llys fod yn dri chymeriad neu fwy",
    listTypeRequired: "Dewiswch fath o restr",
    hearingStartDateRequired: "Rhowch ddyddiad dechrau gwrandawiad dilys",
    hearingStartDateInvalid: "Rhowch ddyddiad dechrau gwrandawiad dilys",
    sensitivityRequired: "Dewiswch lefel sensitifrwydd",
    languageRequired: "Dewiswch iaith",
    displayFromRequired: "Rhowch ddyddiad dangos y ffeil o dilys",
    displayFromInvalid: "Rhowch ddyddiad dangos y ffeil o dilys",
    displayToRequired: "Rhowch ddyddiad dangos y ffeil tan dilys",
    displayToInvalid: "Rhowch ddyddiad dangos y ffeil tan dilys",
    displayToBeforeFrom: "Rhaid i'r dyddiad dangos tan fod ar ôl y dyddiad dangos o"
  }
};
