export const en = {
  title: "Manual upload",
  fileUploadLabel: "Manually upload a csv, doc, docx, htm, html, json, or pdf file, max size 2MB",
  courtLabel: "Court or tribunal name",
  listTypeLabel: "List type",
  listTypePlaceholder: "Please choose a list type",
  hearingStartDateLabel: "Hearing start date",
  hearingStartDateHint: "For example, 16 01 2022",
  sensitivityLabel: "Sensitivity",
  languageLabel: "Language",
  displayFromLabel: "Display file from",
  displayFromHint: "For example, 27 01 2022",
  displayToLabel: "Display file to",
  displayToHint: "For example, 18 02 2022",
  continueButton: "Continue",
  errorSummaryTitle: "There is a problem",
  pageHelpTitle: "Page help",
  pageHelpLists: "Lists",
  pageHelpListsText:
    "You must ensure that you only upload one file that contains all hearings for the Court or Tribunal name and List type. This should include all judges and court rooms in one document.",
  pageHelpSensitivity: "Sensitivity",
  pageHelpSensitivityText: "You need to indicate which user group your document should be available to:",
  pageHelpSensitivityPublic: "Public",
  pageHelpSensitivityPublicText: "Publication available to all users.",
  pageHelpSensitivityPrivate: "Private",
  pageHelpSensitivityPrivateText: "Publication available to all verified users e.g. Legal professionals and media.",
  pageHelpSensitivityClassified: "Classified",
  pageHelpSensitivityClassifiedText:
    "Publication only available to verified users who are in a group eligible to view that list e.g. SJP press list available to Media",
  pageHelpDisplayFrom: "Display from",
  pageHelpDisplayFromText:
    "This will be the date the publication is available from, if today's date is used it will be displayed immediately. If a date in the future is used, it will display from 00:01 of that date.",
  pageHelpDisplayTo: "Display to",
  pageHelpDisplayToText: "This will be the last date the publication is available. It will be displayed until 23:59 of that date.",
  dayLabel: "Day",
  monthLabel: "Month",
  yearLabel: "Year",

  errorMessages: {
    fileRequired: "Please provide a file",
    fileType: "The selected file must be a csv, doc, docx, htm, html, json, or pdf",
    fileSize: "The selected file must be smaller than 2MB",
    courtRequired: "Court name must be three characters or more",
    listTypeRequired: "Please select a list type",
    hearingStartDateRequired: "Please enter a valid hearing start date",
    hearingStartDateInvalid: "Please enter a valid hearing start date",
    sensitivityRequired: "Please select a sensitivity",
    languageRequired: "Select a language",
    displayFromRequired: "Please enter a valid display file from date",
    displayFromInvalid: "Please enter a valid display file from date",
    displayToRequired: "Please enter a valid display file to date",
    displayToInvalid: "Please enter a valid display file to date",
    displayToBeforeFrom: "Display to date must be after display from date"
  }
};
