export const cy = {
  title: "Gweithdrefn Cyfiawnder Sengl – Rhestr y Wasg",
  accordionTitle: "Beth yw Achosion Gweithdrefn Cyfiawnder Sengl?",
  accordionContent: "Achosion sy'n barod i gael eu penderfynu gan ynad heb wrandawiad. Mae'n cynnwys trwyddedu teledu a throseddau traffig bach fel goryrru.",
  listFor: "Rhestr ar gyfer",
  published: "Cyhoeddwyd",
  at: "am",
  importantInfoTitle: "Gwybodaeth Bwysig",
  importantInfoContent:
    "Yn unol â'r protocol cyfryngau, mae dogfennau ychwanegol o'r achosion hyn ar gael i aelodau o'r cyfryngau ar gais. Mae'r ddolen isod yn mynd â chi at y protocol llawn a rhagor o wybodaeth ynghylch pa ddogfennaeth y gellir ei chael",
  mediaProtocolLink: "Protocol ar rannu rhestrau llysoedd, cofrestrau a dogfennau gyda'r cyfryngau",
  downloadButton: "Lawrlwytho copi",
  searchLabel: "Chwilio hidlwyr",
  showFilters: "Dangos hidlwyr",
  hideFilters: "Cuddio hidlwyr",
  postcodeFilterHeading: "Cod post",
  londonPostcodesLabel: "Codau Post Llundain",
  postcodeLabel: "Rhowch god post",
  prosecutorFilterHeading: "Erlynydd",
  prosecutorLabel: "Dewiswch erlynydd",
  selectProsecutor: "Dewiswch erlynydd",
  filterTitle: "Hidlo",
  selectedFilters: "Hidlwyr a ddewiswyd",
  clearFilters: "Clirio hidlwyr",
  applyFilters: "Cymhwyso hidlwyr",
  nameHeader: "Enw",
  dobHeader: "Dyddiad Geni",
  referenceHeader: "Cyfeirnod",
  addressHeader: "Cyfeiriad",
  prosecutorHeader: "Erlynydd",
  reportingRestrictionHeader: "Cyfyngiad Adrodd",
  offenceHeader: "Trosedd",
  noCasesFound: "Dim achosion wedi'u darganfod",
  previous: "Blaenorol",
  next: "Nesaf",
  backToTop: "Yn ôl i'r brig",
  errorSummaryTitle: "Mae problem wedi codi",
  errorInvalidPostcode: "Rhowch god post dilys",
  errorNotVerified: "Rhaid i chi fod yn ddefnyddiwr dilysedig i gael mynediad at restrau'r wasg"
};
