-- Update allowed_provenance for all list types to match the Java pip-data-models enum.
-- Safe to run multiple times (idempotent UPDATE).

-- Multi-provenance magistrates lists (CRIME_IDAM + PI_AAD)
UPDATE list_types
SET allowed_provenance = 'CRIME_IDAM,PI_AAD'
WHERE name IN (
  'MAGISTRATES_PUBLIC_LIST',
  'MAGISTRATES_STANDARD_LIST'
);

-- SJP lists: COMMON_PLATFORM → PI_AAD
UPDATE list_types
SET allowed_provenance = 'PI_AAD'
WHERE name IN (
  'SJP_PRESS_LIST',
  'SJP_PUBLIC_LIST',
  'SJP_DELTA_PRESS_LIST',
  'SJP_DELTA_PUBLIC_LIST'
);

-- Kings Bench Masters + all non-strategic lists: MANUAL_UPLOAD → CFT_IDAM
UPDATE list_types
SET allowed_provenance = 'CFT_IDAM'
WHERE name IN (
  'KINGS_BENCH_MASTERS_DAILY_CAUSE_LIST',
  'SIAC_WEEKLY_HEARING_LIST',
  'POAC_WEEKLY_HEARING_LIST',
  'PAAC_WEEKLY_HEARING_LIST',
  'FTT_TAX_CHAMBER_WEEKLY_HEARING_LIST',
  'FTT_LANDS_REGISTRATION_TRIBUNAL_WEEKLY_HEARING_LIST',
  'FTT_RPT_EASTERN_WEEKLY_HEARING_LIST',
  'FTT_RPT_LONDON_WEEKLY_HEARING_LIST',
  'FTT_RPT_MIDLANDS_WEEKLY_HEARING_LIST',
  'FTT_RPT_NORTHERN_WEEKLY_HEARING_LIST',
  'FTT_RPT_SOUTHERN_WEEKLY_HEARING_LIST',
  'SEND_DAILY_HEARING_LIST',
  'CIC_WEEKLY_HEARING_LIST',
  'AST_DAILY_HEARING_LIST',
  'GRC_WEEKLY_HEARING_LIST',
  'WPAFCC_WEEKLY_HEARING_LIST',
  'UTIAC_STATUTORY_APPEAL_DAILY_HEARING_LIST',
  'UTIAC_JR_LONDON_DAILY_HEARING_LIST',
  'UTIAC_JR_LEEDS_DAILY_HEARING_LIST',
  'UTIAC_JR_MANCHESTER_DAILY_HEARING_LIST',
  'UTIAC_JR_BIRMINGHAM_DAILY_HEARING_LIST',
  'UTIAC_JR_CARDIFF_DAILY_HEARING_LIST',
  'SSCS_MIDLANDS_DAILY_HEARING_LIST',
  'SSCS_SOUTH_EAST_DAILY_HEARING_LIST',
  'SSCS_WALES_AND_SOUTH_WEST_DAILY_HEARING_LIST',
  'SSCS_SCOTLAND_DAILY_HEARING_LIST',
  'SSCS_NORTH_EAST_DAILY_HEARING_LIST',
  'SSCS_NORTH_WEST_DAILY_HEARING_LIST',
  'SSCS_LONDON_DAILY_HEARING_LIST',
  'UT_TAX_AND_CHANCERY_CHAMBER_DAILY_HEARING_LIST',
  'UT_LANDS_CHAMBER_DAILY_HEARING_LIST',
  'UT_ADMINISTRATIVE_APPEALS_CHAMBER_DAILY_HEARING_LIST'
);

-- Verify: show all list types with their updated provenances
-- SELECT name, allowed_provenance, is_non_strategic FROM list_types ORDER BY name;
