export const cy = {
  title: "[Welsh] Upload Excel file",
  pageTitle: "[Welsh] Upload - Upload Excel file",
  warningTitle: "[Welsh] Warning",
  warningMessage:
    "[Welsh] Prior to upload you must ensure the file is suitable for publication e.g. redaction of personal data has been done during the production of this file.",
  fileUploadLabel: "[Welsh] Manually upload an Excel file (.xlsx), max size 2MB",
  courtLabel: "[Welsh] Court name or Tribunal name",
  listTypeLabel: "[Welsh] List type",
  listTypePlaceholder: "[Welsh] Please choose a list type",
  hearingStartDateLabel: "[Welsh] Hearing start date",
  hearingStartDateHint: "[Welsh] For example, 16 01 2022",
  sensitivityLabel: "[Welsh] Sensitivity",
  languageLabel: "[Welsh] Language",
  displayFromLabel: "[Welsh] Display file from",
  displayFromHint: "[Welsh] For example, 27 01 2022",
  displayToLabel: "[Welsh] Display file to",
  displayToHint: "[Welsh] For example, 18 02 2022",
  continueButton: "[Welsh] Continue",
  errorSummaryTitle: "[Welsh] There is a problem",
  pageHelpTitle: "[Welsh] Page help",
  pageHelpLists: "[Welsh] Lists",
  pageHelpListsText:
    "[Welsh] You must ensure that you only upload one file that contains all hearings for the Court or Tribunal name and List type. This should include all judges and court rooms in one document.",
  pageHelpSensitivity: "[Welsh] Sensitivity",
  pageHelpSensitivityText: "[Welsh] You need to indicate which user group your document should be available to:",
  pageHelpSensitivityPublic: "[Welsh] Public",
  pageHelpSensitivityPublicText: "[Welsh] Publication available to all users.",
  pageHelpSensitivityPrivate: "[Welsh] Private",
  pageHelpSensitivityPrivateText: "[Welsh] Publication available to all verified users e.g. Legal professionals and media.",
  pageHelpSensitivityClassified: "[Welsh] Classified",
  pageHelpSensitivityClassifiedText:
    "[Welsh] Publication only available to verified users who are in a group eligible to view that list e.g. SJP press list available to Media.",
  pageHelpDisplayFrom: "[Welsh] Display from",
  pageHelpDisplayFromText: "[Welsh] This will be the date the publication is available from … displayed immediately if today's date is used.",
  pageHelpDisplayTo: "[Welsh] Display to",
  pageHelpDisplayToText: "[Welsh] This will be the last date the publication is available. It will be displayed until 23:59 of that date.",
  dayLabel: "[Welsh] Day",
  monthLabel: "[Welsh] Month",
  yearLabel: "[Welsh] Year",
  backToTop: "[Welsh] Back to top",

  errorMessages: {
    fileRequired: "[Welsh] Please provide a file",
    fileType: "[Welsh] The selected file type is not supported",
    fileSize: "[Welsh] The selected file must be smaller than 2MB",
    courtRequired: "[Welsh] Please enter and select a valid court",
    courtTooShort: "[Welsh] Court name must be three characters or more",
    listTypeRequired: "[Welsh] Please select a list type",
    hearingStartDateRequired: "[Welsh] Please enter a valid hearing start date",
    hearingStartDateInvalid: "[Welsh] Please enter a valid hearing start date",
    sensitivityRequired: "[Welsh] Please select a sensitivity",
    languageRequired: "[Welsh] Select a language option",
    displayFromRequired: "[Welsh] Please enter a valid display file from date",
    displayFromInvalid: "[Welsh] Please enter a valid display file from date",
    displayToRequired: "[Welsh] Please enter a valid display file to date",
    displayToInvalid: "[Welsh] Please enter a valid display file to date",
    displayToBeforeFrom: "[Welsh] 'Display to' date must be the same as or later than 'Display from' date"
  }
};
