# Global values shared by all subcharts
global:
  environment: dev
  security:
    allowInsecureImages: true

# Enable/disable subcharts
postgres:
  enabled: true
web:
  enabled: true
api:
  enabled: true
crons:
  enabled: true

# Web application configuration
cath-web:
  nodejs:
    image: "hmctspublic.azurecr.io/cath/cath-web:${WEB_IMAGE}"
    ingressHost: "{{ .Release.Name }}-web.dev.platform.hmcts.net"
    aadIdentityName: cath
    environment:
      BASE_URL: "https://{{ .Release.Name }}-web.dev.platform.hmcts.net"
      ENABLE_TEST_SUPPORT: "true"
      CFT_IDAM_URL: "https://idam-web-public.aat.platform.hmcts.net"
      SSO_ALLOW_HTTP_REDIRECT: 'true'
      REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379"
      POSTGRES_DATABASE: "{{ .Release.Name }}"
    keyVaults:
      pip-ss-kv:
        secrets:
          - name: sso-client-id
            alias: SSO_CLIENT_ID
          - name: sso-client-secret
            alias: SSO_CLIENT_SECRET
          - name: sso-issuer-url
            alias: SSO_IDENTITY_METADATA
          - name: sso-sg-system-admin
            alias: SSO_SYSTEM_ADMIN_GROUP_ID
          - name: sso-sg-admin-ctsc
            alias: SSO_INTERNAL_ADMIN_CTSC_GROUP_ID
          - name: sso-sg-admin-local
            alias: SSO_INTERNAL_ADMIN_LOCAL_GROUP_ID
          - name: cft-idam-client-secret
            alias: CFT_IDAM_CLIENT_SECRET
          - name: app-pip-b2c-id
            alias: B2C_CLIENT_ID
          - name: app-pip-b2c-pwd
            alias: B2C_CLIENT_SECRET
          - name: b2c-tenant-id
            alias: B2C_TENANT_ID
    secrets:
      POSTGRES_HOST:
        secretRef: postgres
        key: HOST
      POSTGRES_USER:
        secretRef: postgres
        key: USER
      POSTGRES_PASSWORD:
        secretRef: postgres
        key: PASSWORD
      POSTGRES_PORT:
        secretRef: postgres
        key: PORT

# API application configuration
cath-api:
  nodejs:
    image: "hmctspublic.azurecr.io/cath/cath-api:${API_IMAGE}"
    ingressHost: "{{ .Release.Name }}-api.dev.platform.hmcts.net"
    environment:
      POSTGRES_DATABASE: "{{ .Release.Name }}"
      ENABLE_TEST_SUPPORT: "true"
    secrets:
      POSTGRES_HOST:
        secretRef: postgres
        key: HOST
      POSTGRES_USER:
        secretRef: postgres
        key: USER
      POSTGRES_PASSWORD:
        secretRef: postgres
        key: PASSWORD
      POSTGRES_PORT:
        secretRef: postgres
        key: PORT

# Crons application configuration
cath-crons:
  job:
    image: "hmctspublic.azurecr.io/cath/cath-crons:${CRONS_IMAGE}"
    schedule: "*/5 * * * *"
    suspend: false
    kind: CronJob
    environment:
      POSTGRES_DATABASE: "{{ .Release.Name }}"
    secrets:
      POSTGRES_HOST:
        secretRef: postgres
        key: HOST
      POSTGRES_USER:
        secretRef: postgres
        key: USER
      POSTGRES_PASSWORD:
        secretRef: postgres
        key: PASSWORD
      POSTGRES_PORT:
        secretRef: postgres
        key: PORT

# Postgres Prisma Studio service configuration
cath-postgres:
  nodejs:
    image: "hmctspublic.azurecr.io/cath/cath-postgres:${POSTGRES_IMAGE}"
    ingressHost: "{{ .Release.Name }}-postgres.dev.platform.hmcts.net"
    environment:
      POSTGRES_DATABASE: "{{ .Release.Name }}"
    secrets:
      POSTGRES_HOST:
        secretRef: postgres
        key: HOST
      POSTGRES_USER:
        secretRef: postgres
        key: USER
      POSTGRES_PASSWORD:
        secretRef: postgres
        key: PASSWORD
      POSTGRES_PORT:
        secretRef: postgres
        key: PORT

# PostgreSQL database configuration
postgresql:
  enabled: true
  flexibleserver: cath-dev
  setup:
    databases:
      - name: "{{ .Release.Name }}"

# Redis cache configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
  image:
    registry: hmctspublic.azurecr.io
    repository: imported/bitnami/redis
