export { USER_ROLES } from "@hmcts/account";
export { getB2cBaseUrl, getB2cConfig, isB2cConfigured } from "./config/b2c-config.js";
export { getCftIdamConfig, isCftIdamConfigured } from "./config/cft-idam-config.js";
export { configurePassport } from "./config/passport-config.js";
export { isSsoConfigured } from "./config/sso-config.js";
export { requireAuth } from "./middleware/authenticate.js";
export { blockUserAccess, requireRole } from "./middleware/authorise.js";
export { authNavigationMiddleware } from "./middleware/navigation.js";
export { buildNavigationItems, buildVerifiedUserNavigation } from "./middleware/navigation-helper.js";
export { sessionTimeoutMiddleware } from "./middleware/session-timeout.js";
export { GET as b2cCallbackHandler, POST as b2cCallbackPostHandler } from "./pages/b2c-callback/index.js";
export { GET as b2cForgotPasswordHandler } from "./pages/b2c-forgot-password/index.js";
export { GET as b2cLoginHandler } from "./pages/b2c-login/index.js";
export { GET as cftCallbackHandler } from "./pages/cft-callback/index.js";
export { GET as ssoCallbackHandler } from "./pages/sso-callback/index.js";
export { isRejectedCFTRole } from "./role-service/index.js";
export { getTimeoutConfig, isSessionExpired, updateLastActivity } from "./session/timeout-tracker.js";
export type { UserProfile } from "./user-profile.js";
