export const cy = {
  title: "Achosion Gweithdrefn Cyfiawnder Sengl sydd yn barod i'w gwrando (Rhestr lawn)",
  listContaining: "Rhestr yn cynnwys",
  casesText: "achos(ion)",
  generatedOn: "wedi'i gynhyrchu ar",
  at: "am",
  filterTitle: "Hidlo",
  selectedFilters: "Hidlwyr a ddewiswyd",
  searchLabel: "Chwilio hidlwyr",
  showFilters: "Dangos hidlwyr",
  hideFilters: "Cuddio hidlwyr",
  postcodeFilterHeading: "Cod post",
  postcodeLabel: "Rhowch god post",
  londonPostcodesLabel: "Codau Post Llundain",
  prosecutorFilterHeading: "Erlynydd",
  prosecutorLabel: "Dewiswch erlynydd",
  selectProsecutor: "Dewiswch erlynydd",
  clearFilters: "Clirio hidlwyr",
  applyFilters: "Cymhwyso hidlwyr",
  nameHeader: "Enw",
  postcodeHeader: "Cod post",
  offenceHeader: "Trosedd",
  prosecutorHeader: "Erlynydd",
  noCasesFound: "Dim achosion wedi'u darganfod",
  previous: "Blaenorol",
  next: "Nesaf",
  backToTop: "Yn ôl i'r brig",
  errorSummaryTitle: "Mae problem wedi codi",
  errorInvalidPostcode: "Rhowch god post dilys"
};
