export const en = {
  title: "Single Justice Procedure cases that are ready for hearing (Full list)",
  listContaining: "List containing",
  casesText: "case(s)",
  generatedOn: "generated on",
  at: "at",
  filterTitle: "Filter",
  selectedFilters: "Selected filters",
  searchLabel: "Search filters",
  showFilters: "Show filters",
  hideFilters: "Hide filters",
  postcodeFilterHeading: "Postcode",
  postcodeLabel: "Enter postcode",
  londonPostcodesLabel: "London Postcodes",
  prosecutorFilterHeading: "Prosecutor",
  prosecutorLabel: "Select prosecutor",
  selectProsecutor: "Select a prosecutor",
  clearFilters: "Clear filters",
  applyFilters: "Apply filters",
  nameHeader: "Name",
  postcodeHeader: "Postcode",
  offenceHeader: "Offence",
  prosecutorHeader: "Prosecutor",
  noCasesFound: "No cases found",
  previous: "Previous",
  next: "Next",
  backToTop: "Back to top",
  errorSummaryTitle: "There is a problem",
  errorInvalidPostcode: "Enter a valid postcode"
};
