-- 002: sync github 2026-06-18
--
-- Reconciles the requirements baseline with the live state of GitHub Project #43
-- (CaTH Kanban) as of 2026-06-18. Generated by a manual, reviewed sync (not the
-- nightly job) while feat/requirements-doors-db is still unmerged. Matches the
-- conventions of seed.sql and 001_inferred_links.sql.
--
-- Delta captured (gate = "Refined Tickets" and beyond):
--   * 3 NEW requirements:        REQ-0135 (#569), REQ-0136 (#716), REQ-0137 (#729)
--   * 6 STATUS changes:          REQ-0105 (#428), REQ-0107 (#431), REQ-0109 (#436),
--                                REQ-0112 (#467), REQ-0121 (#545), REQ-0132 (#586)
--   * 4 STATUS + IMPL changes:   REQ-0111 (#466), REQ-0119 (#511), REQ-0133 (#594),
--                                REQ-0134 (#678) — moved to verified and gained a
--                                merged closing PR (impl_commit_sha + impl_paths).
--   * 4 REGRESSIONS recorded:    REQ-0126 (#566) in_progress->draft [Backlog],
--                                REQ-0129 (#583), REQ-0130 (#584), REQ-0131 (#585)
--                                approved->proposed [Prioritised Backlog].
--     Recorded as normal status_changed history (the DOORS way: identifiers and
--     baselines are immutable, but a status attribute may regress and the change is
--     logged). Below-gate boards map: Backlog->draft, Prioritised Backlog->proposed.
--     No row is deleted and no ref is reused.
--
-- All affected rows are at version 1, so each edit below bumps them to version 2.

BEGIN TRANSACTION;

-- ============================================================================
-- NEW requirements (REQ-0135..REQ-0137), ordered by issue number.
-- kind defaults to 'functional'; no priority/granularity labels on these issues.
-- ============================================================================
INSERT INTO requirement
  (id, ref, title, statement, kind, status, priority, granularity,
   issue_number, issue_url, impl_commit_sha, impl_paths,
   created_at, updated_at, created_by, updated_by)
VALUES
  (135, 'REQ-0135', 'Add Azure Blob Storage to cath-service infrastructure Terraform', '## User Story

As a platform engineer, I want Azure Blob Storage provisioned for the cath-service so that application files (publication JSON, generated PDFs, media application ID proof images) can be stored in durable cloud storage rather than the local pod filesystem.

## Background

Currently all file storage in cath-service writes to the local filesystem (`storage/temp/uploads`, `storage/temp/files`). Files are lost on every Kubernetes pod restart or redeployment. Azure Blob Storage is the correct durable store for these files.

Both `pip-data-management` and `pip-account-management` use a shared storage account provisioned in [`pip-shared-infrastructures`](https://github.com/hmcts/pip-shared-infrastructures) via `cnp-module-storage-account@4.x`. cath-service needs its own equivalent.

## Infrastructure Changes Required

### 1. New `infrastructure/storage.tf`

Create using `cnp-module-storage-account@4.x` with:

- **Storage account name**: `cathsa${env}` → e.g. `cathsastg`, `cathsaprod`, `cathsaithc`, `cathsademo`, `cathsatest`
- **3 private blob containers**: `artefact`, `files`, `publications`
- **Managed identity access**: reference the existing `cath-${var.env}-mi` (created by `cnp-module-key-vault` when `create_managed_identity = true`) via a `data "azurerm_user_assigned_identity"` lookup in `managed-identities-${var.env}-rg`. Grant it `Storage Blob Data Contributor` role.
- **No separate managed identity is needed** — the existing KV module MI is reused (same pattern as pip-shared-infrastructures)
- Standard settings: StorageV2, Standard tier, RAGRS replication, Cool access tier

### 2. Update `infrastructure/variables.tf`

Add storage account configuration variables (with defaults matching pip pattern):
- `sa_account_tier` — default `"Standard"`
- `sa_account_kind` — default `"StorageV2"`
- `sa_account_replication_type` — default `"RAGRS"`
- `sa_access_tier` — default `"Cool"`

### 3. Add Key Vault secrets

Add `azurerm_key_vault_secret` resources to store:
- `storageaccount-connection-string` → `module.sa.storageaccount_primary_connection_string`
- `storageaccount-name` → `module.sa.storageaccount_name`

### 4. Update Helm values

Update `apps/*/helm/values.yaml` (stg/prod) to inject from Key Vault:
- `storageaccount-name` → alias `AZURE_STORAGE_ACCOUNT_NAME`
- `storageaccount-connection-string` → alias `AZURE_STORAGE_CONNECTION_STRING`

Add `MANAGED_IDENTITY_CLIENT_ID` as a direct environment variable in `values.stg.template.yaml` / `values.prod.template.yaml` (same pip pattern — not from Key Vault, injected directly as the MI client ID for the environment).

## Reference

- `pip-shared-infrastructures/tf-sa-main.tf` — storage account module call
- `pip-shared-infrastructures/main.tf` — `data "azurerm_user_assigned_identity" "app_mi"` pattern
- `pip-shared-infrastructures/tf-kv-secrets.tf` — Key Vault secrets
- `pip-data-management/charts/pip-data-management/values.yaml` — Helm values pattern

## Acceptance Criteria

- [ ] `infrastructure/storage.tf` created using `cnp-module-storage-account@4.x`
- [ ] Storage account named `cathsa${env}` (e.g. `cathsastg`, `cathsaprod`)
- [ ] 3 private containers provisioned: `artefact`, `files`, `publications`
- [ ] Existing `cath-${env}-mi` managed identity granted `Storage Blob Data Contributor` role on the storage account
- [ ] Key Vault secrets `storageaccount-connection-string` and `storageaccount-name` created
- [ ] Helm values updated to inject storage env vars from Key Vault
- [ ] `MANAGED_IDENTITY_CLIENT_ID` injected in stg/prod template values files
- [ ] `terraform plan` produces no errors', 'functional', 'in_progress', NULL, NULL, 569, 'https://github.com/hmcts/cath-service/issues/569', NULL, NULL, '2026-05-12T11:00:17Z', '2026-05-12T11:00:17Z', 'github-actions[bot]', 'github-actions[bot]'),
  (136, 'REQ-0136', 'Create App Registration for CaTH API', 'We need to ask PlatOps team to create App registration for CaTH API Service with role api.publisher.user.

  1. Create cath-service-api app registration
  2. Add api.publisher.user custom app role on it
  3. Grant cath-service-api''s own service principal the api.publisher.user role on itself

By doing this, we will not use pip-data-management app registration anymore.', 'functional', 'verified', NULL, NULL, 716, 'https://github.com/hmcts/cath-service/issues/716', NULL, NULL, '2026-06-12T08:08:48Z', '2026-06-12T08:08:48Z', 'github-actions[bot]', 'github-actions[bot]'),
  (137, 'REQ-0137', 'Make the footer font size the same as in OG CaTH', 'Currently the footer font size in AI CaTH is bigger than the OG CaTH. Make them consistent', 'functional', 'approved', NULL, NULL, 729, 'https://github.com/hmcts/cath-service/issues/729', NULL, NULL, '2026-06-17T09:11:01Z', '2026-06-17T09:11:01Z', 'github-actions[bot]', 'github-actions[bot]');

-- 'created' history for the new requirements (changed_at = issue createdAt).
INSERT INTO requirement_change
  (requirement_id, version, change_type, change_summary, changed_by, changed_at)
VALUES
  (135, 1, 'created', 'imported from GitHub issue', 'github-actions[bot]', '2026-05-12T11:00:17Z'),
  (136, 1, 'created', 'imported from GitHub issue', 'github-actions[bot]', '2026-06-12T08:08:48Z'),
  (137, 1, 'created', 'imported from GitHub issue', 'github-actions[bot]', '2026-06-17T09:11:01Z');

-- ============================================================================
-- STATUS-only changes (board moved forward; no merged PR on these issues).
-- ============================================================================
UPDATE requirement SET status='in_progress', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=105; -- REQ-0105 #428 approved->in_progress
UPDATE requirement SET status='implemented', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=107; -- REQ-0107 #431 approved->implemented
UPDATE requirement SET status='implemented', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=109; -- REQ-0109 #436 approved->implemented
UPDATE requirement SET status='implemented', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=112; -- REQ-0112 #467 in_progress->implemented
UPDATE requirement SET status='verified',    version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=121; -- REQ-0121 #545 implemented->verified
UPDATE requirement SET status='verified',    version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=132; -- REQ-0132 #586 approved->verified

INSERT INTO requirement_change
  (requirement_id, version, field, old_value, new_value, change_type, change_summary, changed_by, changed_at)
VALUES
  (105, 2, 'status', 'approved',    'in_progress', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (107, 2, 'status', 'approved',    'implemented', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (109, 2, 'status', 'approved',    'implemented', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (112, 2, 'status', 'in_progress', 'implemented', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (121, 2, 'status', 'implemented', 'verified',    'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (132, 2, 'status', 'approved',    'verified',    'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z');

-- ============================================================================
-- STATUS + IMPL changes (moved to verified AND gained a merged closing PR).
-- One UPDATE per row, version bumped once, all change rows at the new version.
-- ============================================================================
UPDATE requirement SET status='verified', impl_commit_sha='8aec7a54d61f8a20338c68afcf6c893bcf470fde', impl_paths='["apps/web/src/assets/css/admin-pages.scss","apps/web/src/pages/(admin)/remove-list-search-results/cy.ts","apps/web/src/pages/(admin)/remove-list-search-results/en.ts","apps/web/src/pages/(admin)/remove-list-search-results/index.njk","apps/web/src/pages/(admin)/remove-list-search-results/index.test.ts","apps/web/src/pages/(admin)/remove-list-search-results/index.ts"]', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=111; -- REQ-0111 #466
UPDATE requirement SET status='verified', impl_commit_sha='b5e95289f9b16a5130ce6c0326b76979dc24c102', impl_paths='["apps/postgres/prisma/migrations/20260608155746_remove_channel_sensitivity_from_legacy_third_party_subscription/migration.sql","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/cy.ts","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/en.ts","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/index.njk","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/index.test.ts","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/index.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/cy.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/en.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/index.njk","apps/web/src/pages/(system-admin)/manage-third-party-user/index.test.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/index.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/cy.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/en.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/index.njk","apps/web/src/pages/(system-admin)/manage-third-party-users/index.test.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/index.ts","libs/legacy-third-party-fulfilment/src/queries.test.ts","libs/legacy-third-party-fulfilment/src/queries.ts","libs/legacy-third-party-fulfilment/src/service.ts","libs/list-types/common/src/validation/list-type-validator.test.ts","libs/postgres-prisma/prisma/schema/base.prisma","libs/system-admin-pages/src/index.ts","libs/system-admin-pages/src/third-party-user/queries.test.ts","libs/system-admin-pages/src/third-party-user/queries.ts","libs/system-admin-pages/src/third-party-user/validation.test.ts","libs/system-admin-pages/src/third-party-user/validation.ts"]', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=119; -- REQ-0119 #511
UPDATE requirement SET status='verified', impl_commit_sha='c1a32f8980445875c44f2da95195f915a28d02e7', impl_paths='["apps/web/src/pages/(list-types)/family-daily-cause-list/family-daily-cause-list.njk","libs/list-types/civil-daily-cause-list/src/email-summary/summary-builder.test.ts","libs/list-types/family-daily-cause-list/src/email-summary/summary-builder.test.ts","libs/list-types/family-daily-cause-list/src/email-summary/summary-builder.ts"]', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=133; -- REQ-0133 #594
UPDATE requirement SET status='verified', impl_commit_sha='f12926d172cdd521694d7b8f2b8c2d1fb3b8f28a', impl_paths='["apps/web/src/pages/(public)/courts-tribunals-list/index.test.ts","e2e-tests/utils/seed-reference-data.ts","libs/list-types/common/src/validation/list-type-validator.test.ts","libs/location/src/location-data.ts"]', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=134; -- REQ-0134 #678

INSERT INTO requirement_change
  (requirement_id, version, field, old_value, new_value, change_type, change_summary, changed_by, changed_at)
VALUES
  (111, 2, 'status', 'implemented', 'verified', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (111, 2, 'impl_commit_sha', NULL, '8aec7a54d61f8a20338c68afcf6c893bcf470fde', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (111, 2, 'impl_paths', NULL, '["apps/web/src/assets/css/admin-pages.scss","apps/web/src/pages/(admin)/remove-list-search-results/cy.ts","apps/web/src/pages/(admin)/remove-list-search-results/en.ts","apps/web/src/pages/(admin)/remove-list-search-results/index.njk","apps/web/src/pages/(admin)/remove-list-search-results/index.test.ts","apps/web/src/pages/(admin)/remove-list-search-results/index.ts"]', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (119, 2, 'status', 'implemented', 'verified', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (119, 2, 'impl_commit_sha', NULL, 'b5e95289f9b16a5130ce6c0326b76979dc24c102', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (119, 2, 'impl_paths', NULL, '["apps/postgres/prisma/migrations/20260608155746_remove_channel_sensitivity_from_legacy_third_party_subscription/migration.sql","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/cy.ts","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/en.ts","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/index.njk","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/index.test.ts","apps/web/src/pages/(system-admin)/manage-third-party-subscriptions/index.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/cy.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/en.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/index.njk","apps/web/src/pages/(system-admin)/manage-third-party-user/index.test.ts","apps/web/src/pages/(system-admin)/manage-third-party-user/index.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/cy.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/en.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/index.njk","apps/web/src/pages/(system-admin)/manage-third-party-users/index.test.ts","apps/web/src/pages/(system-admin)/manage-third-party-users/index.ts","libs/legacy-third-party-fulfilment/src/queries.test.ts","libs/legacy-third-party-fulfilment/src/queries.ts","libs/legacy-third-party-fulfilment/src/service.ts","libs/list-types/common/src/validation/list-type-validator.test.ts","libs/postgres-prisma/prisma/schema/base.prisma","libs/system-admin-pages/src/index.ts","libs/system-admin-pages/src/third-party-user/queries.test.ts","libs/system-admin-pages/src/third-party-user/queries.ts","libs/system-admin-pages/src/third-party-user/validation.test.ts","libs/system-admin-pages/src/third-party-user/validation.ts"]', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (133, 2, 'status', 'implemented', 'verified', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (133, 2, 'impl_commit_sha', NULL, 'c1a32f8980445875c44f2da95195f915a28d02e7', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (133, 2, 'impl_paths', NULL, '["apps/web/src/pages/(list-types)/family-daily-cause-list/family-daily-cause-list.njk","libs/list-types/civil-daily-cause-list/src/email-summary/summary-builder.test.ts","libs/list-types/family-daily-cause-list/src/email-summary/summary-builder.test.ts","libs/list-types/family-daily-cause-list/src/email-summary/summary-builder.ts"]', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (134, 2, 'status', 'implemented', 'verified', 'status_changed', 'board status moved', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (134, 2, 'impl_commit_sha', NULL, 'f12926d172cdd521694d7b8f2b8c2d1fb3b8f28a', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (134, 2, 'impl_paths', NULL, '["apps/web/src/pages/(public)/courts-tribunals-list/index.test.ts","e2e-tests/utils/seed-reference-data.ts","libs/list-types/common/src/validation/list-type-validator.test.ts","libs/location/src/location-data.ts"]', 'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-06-18T00:00:00Z');

-- ============================================================================
-- REGRESSIONS — issues that moved BELOW the gate since the baseline. Recorded
-- as status_changed history (DOORS: log the regression, never delete/reuse a
-- ref). Below-gate mapping: Backlog->draft, Prioritised Backlog->proposed.
-- Flagged for human attention in the PR body.
-- ============================================================================
UPDATE requirement SET status='draft',    version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=126; -- REQ-0126 #566 Backlog
UPDATE requirement SET status='proposed', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=129; -- REQ-0129 #583 Prioritised Backlog
UPDATE requirement SET status='proposed', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=130; -- REQ-0130 #584 Prioritised Backlog
UPDATE requirement SET status='proposed', version=version+1, updated_at='2026-06-18T00:00:00Z' WHERE id=131; -- REQ-0131 #585 Prioritised Backlog

INSERT INTO requirement_change
  (requirement_id, version, field, old_value, new_value, change_type, change_summary, changed_by, changed_at)
VALUES
  (126, 2, 'status', 'in_progress', 'draft',    'status_changed', 'board status regressed below gate (Backlog)',             'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (129, 2, 'status', 'approved',    'proposed', 'status_changed', 'board status regressed below gate (Prioritised Backlog)', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (130, 2, 'status', 'approved',    'proposed', 'status_changed', 'board status regressed below gate (Prioritised Backlog)', 'github-actions[bot]', '2026-06-18T00:00:00Z'),
  (131, 2, 'status', 'approved',    'proposed', 'status_changed', 'board status regressed below gate (Prioritised Backlog)', 'github-actions[bot]', '2026-06-18T00:00:00Z');

COMMIT;
