-- 010: sync github 2026-07-24
--
-- Reconciles the requirements baseline with the live state of GitHub Project #43
-- (CaTH Kanban) as of 2026-07-24. Generated by the nightly requirements-sync job.
--
-- NOTE: The GitHub App token used by this job does not have read:project permission,
-- so board column status cannot be read directly from ProjectV2. Closure of the
-- GitHub issue + presence of a merged closing PR is used as a proxy for
-- Done=verified.
--
-- Delta captured (gate = "Refined Tickets" and beyond):
--   * 1 NEW requirement (REQ-0157):
--       #859
--   * 2 status changes:
--       REQ-0098 (#342): approved -> verified
--       REQ-0099 (#343): implemented -> verified
--   * 1 impl change:
--       REQ-0099 (#343): new merged PR (sha + paths)

BEGIN TRANSACTION;

-- ============================================================================
-- NEW REQUIREMENTS (1 issue, closed with merged closing PR)
-- ============================================================================

INSERT INTO requirement
  (id, ref, title, statement, kind, status, priority, granularity,
   issue_number, issue_url, impl_commit_sha, impl_paths,
   created_at, updated_at, created_by, updated_by)
VALUES
  (157, 'REQ-0157', 'Style Guide: Implement High Court manual-upload daily cause lists (Business & Property, Circuit Commercial, HC Civil, HC Family)', 'As a user, I want to view the following High Court daily cause lists that have been manually uploaded as flat files, so that I can access scheduled hearing information.', 'functional', 'verified', NULL, 'story', 859, 'https://github.com/hmcts/cath-service/issues/859', 'c74ad165fc754ea590a19d844d162381cec3cf9d', '["apps/postgres/prisma/scripts/001_insert_missing_list_types.sql","apps/postgres/prisma/scripts/003_upsert_sub_jurisdictions_and_list_type_links.sql","libs/list-types/common/src/list-type-data.test.ts","libs/list-types/common/src/list-type-data.ts"]', '2026-07-15T08:49:48Z', '2026-07-15T08:49:48Z', 'junaidiqbalmoj', 'junaidiqbalmoj');

INSERT INTO requirement_change
  (requirement_id, version, change_type, change_summary, changed_by, changed_at)
VALUES
  (157, 1, 'created', 'imported from GitHub issue', 'github-actions[bot]', '2026-07-15T08:49:48Z');

-- ============================================================================
-- STATUS CHANGES (2 requirements)
-- ============================================================================

-- REQ-0098 (#342): approved -> verified (issue closed, no merged PR)
UPDATE requirement
SET status = 'verified',
    version = version + 1,
    updated_at = '2026-07-24T00:00:00Z',
    updated_by = 'github-actions[bot]'
WHERE id = 98;

INSERT INTO requirement_change
  (requirement_id, version, field, old_value, new_value,
   change_type, change_summary, changed_by, changed_at)
VALUES
  (98, 2, 'status', 'approved', 'verified',
   'status_changed', 'board status moved', 'github-actions[bot]', '2026-07-24T00:00:00Z');

-- REQ-0099 (#343): implemented -> verified (issue closed with merged PR)
-- Combined status + impl change: one UPDATE, version bumps once.
UPDATE requirement
SET status = 'verified',
    impl_commit_sha = 'daaf5f49099710810ace858ae70a170f0c41f27c',
    impl_paths = '["e2e-tests/tests/api/subscription-notifications.spec.ts","e2e-tests/utils/test-support-api.ts","libs/notifications/src/govnotify/govnotify-client.test.ts","libs/notifications/src/govnotify/govnotify-client.ts","libs/notifications/src/govnotify/template-config.test.ts","libs/notifications/src/govnotify/template-config.ts","libs/notifications/src/notification/notification-service.test.ts","libs/notifications/src/notification/notification-service.ts"]',
    version = version + 1,
    updated_at = '2026-07-24T00:00:00Z',
    updated_by = 'github-actions[bot]'
WHERE id = 99;

INSERT INTO requirement_change
  (requirement_id, version, field, old_value, new_value,
   change_type, change_summary, changed_by, changed_at)
VALUES
  (99, 2, 'status', 'implemented', 'verified',
   'status_changed', 'board status moved', 'github-actions[bot]', '2026-07-24T00:00:00Z'),
  (99, 2, 'impl_commit_sha', NULL, 'daaf5f49099710810ace858ae70a170f0c41f27c',
   'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-07-24T00:00:00Z'),
  (99, 2, 'impl_paths', NULL, '["e2e-tests/tests/api/subscription-notifications.spec.ts","e2e-tests/utils/test-support-api.ts","libs/notifications/src/govnotify/govnotify-client.test.ts","libs/notifications/src/govnotify/govnotify-client.ts","libs/notifications/src/govnotify/template-config.test.ts","libs/notifications/src/govnotify/template-config.ts","libs/notifications/src/notification/notification-service.test.ts","libs/notifications/src/notification/notification-service.ts"]',
   'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-07-24T00:00:00Z');

COMMIT;
