-- 013: sync github 2026-07-31
--
-- Reconciles the requirements baseline with the live state of GitHub Project #43
-- (CaTH Kanban) as of 2026-07-31. Generated by the nightly requirements-sync job.
--
-- NOTE: The GitHub App token used by this job does not have read:project permission,
-- so board column status cannot be read directly from ProjectV2. Instead, closure
-- of the GitHub issue + presence of a merged closing PR is used as a proxy for
-- Done=verified. A human reviewer should confirm the board position before merging.
--
-- Delta captured (gate = "Refined Tickets" and beyond):
--   * 0 NEW requirements
--   * 1 STATUS + IMPL change (closed issue + merged closing PR -> verified):
--       REQ-0110 (#438): approved -> verified
--         PR #863 (feat(#438): register PCOL Daily Cause List flat-file list type)
--         merged 2026-07-30T08:58:10Z
--         merge commit: 5421d745490bedae826e03b78e61d8ae6146def7
--
-- Numbered 013 because this migration is stacked on 012 (sync 2026-07-30) on the
-- same branch, and 011 is taken by the open rework PR #905.
--
-- Applying the documented exclusion rules to the fully-paged closing-PR file
-- lists reproduces impl_commit_sha and impl_paths exactly for all 58 previously
-- implemented requirements once 012 is applied, so REQ-0110 is the only drift
-- in this window.
--
-- HUMAN REVIEW REQUIRED: Board access unavailable; verify REQ-0110 (#438) is
-- actually in the "Done" column on the CaTH Kanban before merging.

BEGIN TRANSACTION;

-- ============================================================================
-- REQ-0110 (#438): approved -> verified + impl_commit_sha + impl_paths
-- PR #863 merged 2026-07-30T08:58:10Z
-- ============================================================================
UPDATE requirement
  SET status          = 'verified',
      impl_commit_sha = '5421d745490bedae826e03b78e61d8ae6146def7',
      impl_paths      = '["libs/list-types/common/src/list-type-data.test.ts","libs/list-types/common/src/list-type-data.ts","libs/notifications/src/govnotify/template-config.test.ts","libs/notifications/src/govnotify/template-config.ts"]',
      version         = version + 1,
      updated_at      = '2026-07-31T00:00:00Z',
      updated_by      = 'github-actions[bot]'
  WHERE id = 110;

INSERT INTO requirement_change
  (requirement_id, version, field, old_value, new_value,
   change_type, change_summary, changed_by, changed_at)
VALUES
  (110, 2, 'status', 'approved', 'verified',
   'status_changed', 'board status moved', 'github-actions[bot]', '2026-07-31T00:00:00Z'),
  (110, 2, 'impl_commit_sha', NULL, '5421d745490bedae826e03b78e61d8ae6146def7',
   'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-07-31T00:00:00Z'),
  (110, 2, 'impl_paths', NULL, '["libs/list-types/common/src/list-type-data.test.ts","libs/list-types/common/src/list-type-data.ts","libs/notifications/src/govnotify/template-config.test.ts","libs/notifications/src/govnotify/template-config.ts"]',
   'modified', 'merged PR(s) changed', 'github-actions[bot]', '2026-07-31T00:00:00Z');

COMMIT;
