export const en = {
  title: "Reference data upload summary",
  pageTitle: "Reference data upload summary",
  fileLabel: "File",
  changeLink: "change",
  confirmButtonText: "Confirm",
  previewTitle: "Preview of data to be uploaded",
  locationIdHeader: "Location ID",
  locationNameHeader: "Location Name",
  welshLocationNameHeader: "Welsh Location Name",
  emailHeader: "Email",
  contactNoHeader: "Contact Number",
  jurisdictionHeader: "Jurisdiction",
  subJurisdictionHeader: "Sub-Jurisdiction",
  regionHeader: "Region",
  provenanceHeader: "Provenance",
  provenanceLocationIdHeader: "Provenance Location ID",
  provenanceLocationTypeHeader: "Provenance Location Type",
  errorSummaryTitle: "There is a problem",
  errorTitle: "Unable to upload reference data file"
};
