export const cy = {
  backLink: "Yn ôl",
  pageTitle: "Dod o hyd i, diweddaru a dileu defnyddiwr",
  filterHeading: "Hidlydd",
  selectedFiltersHeading: "Hidlwyr a ddewiswyd",
  emailLabel: "E-bost",
  userIdLabel: "ID Defnyddiwr",
  userIdHint: "Rhaid iddo fod yn union yr un fath",
  userProvenanceIdLabel: "ID Tarddiad Defnyddiwr",
  userProvenanceIdHint: "Rhaid iddo fod yn union yr un fath",
  roleLabel: "Rôl",
  rolesLabel: "Rolau",
  provenanceLabel: "Tarddiad",
  provenancesLabel: "Tarddiannau",
  applyFiltersButton: "Cymhwyso hidlwyr",
  clearFiltersButton: "Clirio hidlwyr",
  tableHeadEmail: "E-bost",
  tableHeadRole: "Rôl",
  tableHeadProvenance: "Tarddiad",
  tableHeadManage: "",
  manageLink: "Rheoli",
  paginationPrevious: "Blaenorol",
  paginationNext: "Nesaf",
  paginationLabel: (current: number, total: number) => `Tudalen ${current} o ${total}`,
  resultsCount: (count: number) => `${count} defnyddiwr wedi'i ganfod`,
  noResultsError: "Ni ellid dod o hyd i unrhyw ddefnyddwyr sy'n cyfateb i'ch meini prawf chwilio. Ceisiwch addasu neu glirio'r hidlwyr.",
  errorSummaryTitle: "Mae problem",
  roleVerified: "Wedi'i wirio",
  roleCtscAdmin: "Gweinyddwr CTSC",
  roleLocalAdmin: "Gweinyddwr Lleol",
  roleSystemAdmin: "Gweinyddwr System",
  provenanceCftIdam: "CFT IdAM",
  provenanceSso: "SSO",
  provenanceB2c: "B2C",
  provenanceCrimeIdam: "Crime IdAM"
};
