nodejs:
  releaseNameOverride: "{{ .Release.Name }}-api"
  applicationPort: 3001
  aadIdentityName: cath
  ingressHost: cath-api.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/cath/cath-api:latest'
  environment:
    NODE_ENV: 'production'
    POSTGRES_DATABASE: cath
  keyVaults:
    cath:
      secrets:
        - name: app-insights-connection-string
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: redis-url
          alias: REDIS_URL
        - name: postgres-url
          alias: DATABASE_URL
        - name: app-tenant-id
          alias: AZURE_TENANT_ID
        - name: app-pip-data-management-id
          alias: AZURE_CLIENT_ID
        - name: app-pip-data-management-scope
          alias: AZURE_SCOPE
