nodejs:
  releaseNameOverride: "{{ .Release.Name }}-api"
  applicationPort: 3001
  aadIdentityName: cath
  ingressHost: cath-api.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/cath/cath-api:latest'
  environment:
    NODE_ENV: 'production'
    POSTGRES_DATABASE: cath
    GOVUK_NOTIFY_TEMPLATE_ID_SUBSCRIPTION: 5b5c31d0-27a3-466b-b750-bd1a858cd50f
    GOVUK_NOTIFY_TEMPLATE_ID_SUBSCRIPTION_PDF_ONLY: ac63ed12-c179-416d-b9af-83b2b37752bf
  keyVaults:
    cath:
      secrets:
        - name: app-insights-connection-string
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: redis-url
          alias: REDIS_URL
        - name: postgres-url
          alias: DATABASE_URL
        - name: app-tenant-id
          alias: AZURE_TENANT_ID
        - name: app-pip-data-management-id
          alias: AZURE_CLIENT_ID
        - name: app-pip-data-management-scope
          alias: AZURE_SCOPE
