export const en = {
  introMessage: "You can use this service to get information about:",
  hearingsList: [
    "Hearings in Civil and Family Courts in England and Wales",
    "Hearings in First Tier and Upper Tribunals (excluding Employment Tribunals)",
    "Hearings in the Royal Courts of Justice and the Rolls Building",
    "Hearings in Crown Courts in England and Wales",
    "Hearings in Magistrates' Courts in England and Wales",
    "Single Justice Procedure cases, including TV licensing and minor traffic offences such as speeding"
  ],
  additionalInfo: "More courts and tribunals will become available over time.",
  signInText: "Legal and media professionals can",
  signInLink: "sign in",
  welshAvailableText: "This service is also available in",
  welshAvailableLink: "Welsh (Cymraeg)",
  continueButton: "Continue",
  factSectionTitle: "Find a court or tribunal",
  factSectionText: "Find contact details and other information about courts and tribunals",
  factSectionTextSuffix: " in England and Wales, and some non-devolved tribunals in Scotland.",
  factLinkUrl: "https://www.gov.uk/find-court-tribunal",
  factLinkText: "Find contact details and other information about courts and tribunals",
  beforeYouStartTitle: "Before you start",
  scotlandNorthernIrelandTitle: "If you're in Scotland or Northern Ireland",
  contactText: "Contact the:",
  scottishCourtsText: " for courts and some tribunals in Scotland",
  scottishCourtsLink: "Scottish Courts website",
  scottishCourtsUrl: "https://www.scotcourts.gov.uk",
  niCourtsText: " for courts and tribunals in Northern Ireland",
  niCourtsLink: "Northern Ireland Courts and Tribunals Service",
  niCourtsUrl: "https://www.justice-ni.gov.uk/topics/courts-and-tribunals"
};
