# Pipeline Deployment Helm Values
# This file is used by Flux for non-prod and prod deployments
# For local development, see values.dev.yaml

nodejs:
  releaseNameOverride: "{{ .Release.Name }}-web"
  applicationPort: 8080
  aadIdentityName: cath
  ingressHost: cath-web.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/cath/cath-web:latest'
  environment:
    NODE_ENV: 'production'
    POSTGRES_DATABASE: cath
    CFT_IDAM_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    CATH_SERVICE_URL: https://cath-web.{{ .Values.global.environment }}.platform.hmcts.net
    GOVUK_NOTIFY_TEMPLATE_ID_SUBSCRIPTION: 5b5c31d0-27a3-466b-b750-bd1a858cd50f
    GOVUK_NOTIFY_TEMPLATE_ID_SUBSCRIPTION_PDF_AND_SUMMARY: ebc08910-5dd5-44c5-b3fc-72f90935f858
    GOVUK_NOTIFY_TEMPLATE_ID_SUBSCRIPTION_SUMMARY_ONLY: bf0802f9-3199-4774-a0c1-f9cb1755ff8f
    GOVUK_NOTIFY_TEMPLATE_ID_MEDIA_APPROVAL: 91d93e44-0ad8-4782-8ef0-fb1cad0c641f
    GOVUK_NOTIFY_TEMPLATE_ID_MEDIA_REJECTION: 838be14a-1ca2-408f-a4bc-a8b4d3c7d54d
  keyVaults:
    cath:
      secrets:
        - name: app-insights-connection-string
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: redis-url
          alias: REDIS_URL
        - name: postgres-url
          alias: DATABASE_URL
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: sso-client-id
          alias: SSO_CLIENT_ID
        - name: sso-client-secret
          alias: SSO_CLIENT_SECRET
        - name: sso-issuer-url
          alias: SSO_IDENTITY_METADATA
        - name: sso-sg-system-admin
          alias: SSO_SYSTEM_ADMIN_GROUP_ID
        - name: sso-sg-admin-ctsc
          alias: SSO_INTERNAL_ADMIN_CTSC_GROUP_ID
        - name: sso-sg-admin-local
          alias: SSO_INTERNAL_ADMIN_LOCAL_GROUP_ID
        - name: cft-idam-client-secret
          alias: CFT_IDAM_CLIENT_SECRET
        # Third-party push secrets - disabled until secrets are added to the cath Key Vault
        # - name: auto-pip-stg-courtel-api
        #   alias: COURTEL_API_URL
        # - name: courtel-certificate
        #   alias: COURTEL_CERTIFICATE
