# Local development overrides only
# Applied on top of values.yaml via: helm install -f values.yaml -f values.dev.yaml
nodejs:
  environment:
    CFT_IDAM_URL: 'https://idam-web-public.aat.platform.hmcts.net'
  keyVaults:
    pip-ss-kv-stg:
      secrets:
        - name: sso-client-id-dev
          alias: SSO_CLIENT_ID
        - name: sso-client-secret-dev
          alias: SSO_CLIENT_SECRET
        - name: sso-issuer-url
          alias: SSO_IDENTITY_METADATA
        - name: sso-sg-system-admin
          alias: SSO_SYSTEM_ADMIN_GROUP_ID
        - name: sso-sg-admin-ctsc
          alias: SSO_INTERNAL_ADMIN_CTSC_GROUP_ID
        - name: sso-sg-admin-local
          alias: SSO_INTERNAL_ADMIN_LOCAL_GROUP_ID
        - name: cft-idam-client-secret
          alias: CFT_IDAM_CLIENT_SECRET
        - name: gov-uk-notify-test-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: b2c-tenant-id
          alias: AZURE_B2C_TENANT_ID
        - name: auto-pip-stg-pip-account-management-stg-id
          alias: AZURE_B2C_CLIENT_ID
        - name: auto-pip-stg-pip-account-management-stg-pwd
          alias: AZURE_B2C_CLIENT_SECRET
        - name: b2c-ad-url
          alias: AZURE_B2C_DOMAIN
