# Pipeline Deployment Helm Values
# This file is used by Flux for non-prod and prod deployments
# For local development, see values.dev.yaml

nodejs:
  applicationPort: 8080
  aadIdentityName: cath
  ingressHost: cath-web.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/cath/cath-web:latest'
  environment:
    POSTGRES_DATABASE: cath
  keyVaults:
    cath:
      secrets:
        - name: app-insights-connection-string
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: redis-url
          alias: REDIS_URL
        - name: postgres-url
          alias: DATABASE_URL
    pip-ss-kv:
      secrets:
        - name: sso-client-id
          alias: SSO_CLIENT_ID
        - name: sso-client-secret
          alias: SSO_CLIENT_SECRET
        - name: sso-issuer-url
          alias: SSO_IDENTITY_METADATA
        - name: sso-sg-system-admin
          alias: SSO_SYSTEM_ADMIN_GROUP_ID
        - name: sso-sg-admin-ctsc
          alias: SSO_INTERNAL_ADMIN_CTSC_GROUP_ID
        - name: sso-sg-admin-local
          alias: SSO_INTERNAL_ADMIN_LOCAL_GROUP_ID
        - name: cft-idam-client-secret
          alias: CFT_IDAM_CLIENT_SECRET
